name: CI/CD Pipeline for OrderService

on:
  push:
    branches:
      - testbranche

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run All Tests
      - name: Run All Tests
        working-directory: ./OrderManagementServiceTests
        run: |
          # Restore dependencies
          dotnet restore OrderManagementServiceTests.csproj
          # Run all tests with results output
          dotnet test OrderManagementServiceTests.csproj --no-build --verbosity normal --logger:"trx;LogFileName=TestResults.trx"

      # Step 3: Upload Test Results after
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./OrderManagementServiceTests/TestResults.trx

